name: 打包 Windows EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js 16
        uses: setup-node@v4
        with:
          node-version: 16

      - name: 安装依赖
        run: npm install --legacy-peer-deps

      # ✅ 直接设置环境变量，强制不上传！这是终极解法！
      - name: 打包
        run: |
          set GH_TOKEN=none
          npm run build:win

      # ✅ 保存所有打包好的文件
      - name: 保存安装包
        uses: upload-artifact@v4
        with:
          name: my-exe
          path: build/
