name: 打包Windows EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: 安装依赖
        run: npm install --legacy-peer-deps

      - name: 先编译项目
        run: npm run build:clean

      # 👇 唯一能跑的命令！单个64位 + 跳过缺失文件 + 不上传
      - name: 打包 64位 EXE
        run: npx electron-builder --win --x64 --publish=never --ignore=vpnagent
        env:
          GH_TOKEN: "skip"

      - name: 保存安装包
        uses: actions/upload-artifact@v4
        with:
          name: my-exe
          path: build/
